fix(#59): TypeError: default is not a function
We're shipping both `./dist/vitest-fail-on-console.es.js` and `./dist/vitest-fail-on-console.umd.js` with "type": "module".
Since Vitest only runs `esm` in the test environment (doesn't use require), we can only ship the default export as `./dist/vitest-fail-on-console.es.js`

Thanks to @hi-ogawa - https://github.com/vitest-dev/vitest/issues/6352#issuecomment-2294477456